import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Ninjas.module.css'
export const getStaticProps  = async () => {
	const res = await fetch('https://jsonplaceholder.typicode.com/users');
	const data = await res.json();
	
	return {
		props: { ninjas: data}
	}
}

const Index = ({ ninjas }) => {
	console.log(ninjas);
  return ( 
		<>
		  <Head>
        <title> Ninja List | Ninja Listing </title>
        <meta name="keywords" content="Ninjas" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div>
        <h2 className={styles.header}> Ninja Listing </h2>
				{ninjas.map(ninja => (
          <Link href={`/ninjas/${ninja.id}`} key={ninja.id}>
						<a className={styles.single}>
							<h3 className={styles.mingle}> {ninja.name} - {ninja.phone} </h3>
						</a>
					</Link>
				))}
      </div>
		</>  
  );
}
 
export default Index;