import Head from 'next/head'
import styles from '../styles/Home.module.css'

const About = () => {

  return (  
    <>
      <Head>
        <title> Ninja List | About </title>
        <meta name="keywords" content="Ninjas" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div>
        <h1> About </h1>
        <p>
          Loren ipsum dolor sit amet consectetur,
          adipisicing elit. Corporis enim at ducimus
          molestiae a magni natus perspiciatis. Fugi
          non laboriosam quisnobis voluptatum tempora,
          veritatis, officia rerum fugiat asperiores illium?
        </p>
        <p>
          Loren ipsum dolor sit amet consectetur,
          adipisicing elit. Corporis enim at ducimus
          molestiae a magni natus perspiciatis. Fugi
          non laboriosam quisnobis voluptatum tempora,
          veritatis, officia rerum fugiat asperiores illium?
        </p>
      </div>
    </>
  );
}
 
export default About;